export const INCREMENT_TEST_NUM = 'INCREMENT_TEST_NUM';
export const DECREMENT_TEST_NUM = 'DECREMENT_TEST_NUM';
export const SAVE_COMMENT = 'SAVE_COMMENT';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
